#!/home/mark_moby_wilkinson/.rvm/rubies/ruby-2.5.1/bin/ruby
require_relative 'fair_metrics_utilities'
require 'cgi'
require 'json'
require 'uri'
require 'rdf'
require 'rdf/turtle'
require 'sparql'

debug = false
VERSION = HARVESTER_VERSION + ":" + "Tst-0.0.1"

# @prefix dcat: <http://www.w3.org/ns/dcat#>.
# @prefix dct: <http://purl.org/dc/terms/>.
# @prefix foaf: <http://xmlns.com/foaf/0.1/>.
# @prefix language: <http://id.loc.gov/vocabulary/iso639-1/>.
# @prefix tes: <http://testbed.ejprd.semlab-leiden.nl:10000/>.
# @prefix c: <http://testbed.ejprd.semlab-leiden.nl:10000/catalog/>.
# @prefix n: <http://www.w3.org/2006/vcard/ns#>.
# @prefix n0: <https://herculescrue.github.io/ROH/roh/#>.
# @prefix voc: <https://w3id.org/ejp-rd/vocabulary#>.

# tes:new
#     a dcat:Dataset, dcat:Resource;
#     dct:description "An example dataset";
#     dct:isPartOf c:cdbe703b-aaa9-4119-a35e-18eb2e8d47d0;
#     dct:keyword "test";
#     dct:language language:en;
#     dct:license <https://w3id.org/ejp-rd/resources/licenses/v1.0.txt>;
#     dct:publisher [ a foaf:Agent; foaf:name "Mark Denis Wilkinson" ];
#     dct:title "A minimal dataset";
#     dcat:contactPoint [ a n:Agent; n:url <https://wilkinsonlab.info> ];
#     dcat:theme n0:Administrative;
#     voc:personalData "false".


def testGUID

	@swagger.addComment("INFO: TEST VERSION '#{VERSION}'\n")
	
	
	guid = @swagger.testedGUID
	
	metadata = Utils::resolveit(guid)  # this is where the magic happens!

	metadata.comments.each do |c|
		@swagger.addComment(c)
	end

	@swagger.score = 0

	if metadata.guidtype == "unknown"
		@swagger.addComment("FAILURE: The identifier #{guid} did not match any known identification system.\n")
		return @swagger.createEvaluationResponse
	end
		
	g = metadata.graph
	if @swagger.debug
		g.each {|s| $stderr.puts s.subject.to_s + "\tPRED: " + s.predicate.to_s + "\tOBJ: " + s.object.to_s + "\n"}
	end

	if g.size > 0  # have we found anything yet?
		@swagger.addComment "INFO: found linked-data style structured metadata.  "
	else
		@swagger.addComment "FAILURE: no linked-data style structured metadata found.  "
		@swagger.score = 0
		return @swagger.createEvaluationResponse
	end

	runtest(g: g)	
	return @swagger.createEvaluationResponse
end

def runtest(g:)
	prefixes = "PREFIX dcat: <http://www.w3.org/ns/dcat#> 
	PREFIX dct: <http://purl.org/dc/terms/> 
	"
	
	classes = %w{https://w3id.org/ejp-rd/vocabulary#PatientRegistry https://w3id.org/ejp-rd/vocabulary#Biobank }

	
	successflag = false
	classes.each do |classs|
		@swagger.addComment "INFO:  Testing if it is a #{classs}.\n"
		classquery = SPARQL.parse("#{prefixes} 
						select ?s where {
							?s a <#{classs}> .
		}")
		results = classquery.execute(g)
		if results.any?
			@swagger.addComment "INFO: Found the EJP class #{classs} \n"
			successflag = true
		else
			@swagger.addComment "WARN: this is not a #{classs}. Moving on\n"
		end
	end
	unless successflag
		@swagger.addComment "INFO: This test should not be run on this class type. You will pass. \n"
		@swagger.score = 1
	else
		# it is at least a legal clas, now check for property
		@swagger.addComment "INFO: Testing for the populationCoverage predicate \n"
		propertyquery = SPARQL.parse("#{prefixes} 
			select ?o where {
				?s <https://w3id.org/ejp-rd/vocabulary#populationCoverage> ?pop .
				?pop <http://www.w3.org/2000/01/rdf-schema#label> ?o 
		}")
		results = propertyquery.execute(g)
		if results.any?
			if ["National", "International", "Regional", "European"].include? results&.first[:o]&.value
				@swagger.score = 1
				@swagger.addComment "SUCCESS: Found a valid population coverage of #{results.first[:o].value}\n"
			else 
				@swagger.addComment "FAILURE: #{results.first[:o].value} is not a valid value for EJP population coverage\n"
			end
		else
			@swagger.addComment "FAILURE: EJP Biobanks and Registries are recommended to include a population coverage of National, Regional, International, or European\n"
		end
	end
end



if debug
	@input = '{"subject": "10.5281/zenodo.1065973"}'  # doi fail

else 
	@input = $stdin.read
end

ENV['TEST_PROTOCOL'] ||= "http"
ENV['TEST_HOST'] ||= "http://tests:8080s"
ENV['TEST_PATH'] ||= "/tests/"

cgi = CGI.new

schemas = {'subject' => ['string', "the GUID being tested"]}

@swagger = Swagger.new({
			:title => "FAIR Metrics for EJP - Registry and Biobank",
			:description => "Tests whether the EJP Registry or Biobank has reccomended populationCoverage",
			:tests_metric => 'https://purl.org/fair-metrics/Gen2_FM_R1.3',
			:version => VERSION,
			:applies_to_principle => "R1.3",
			:organization => 'EJP Metrics Authoring Group',
			:org_url => 'https://ejprdproject.org',
			:responsible_developer => "Mark D Wilkinson",
			:email => 'mark.wilkinson@upm.es',
			:developer_ORCiD => '0000-0001-6960-357X',
			:protocol => ENV['TEST_PROTOCOL'],
			:host => ENV['TEST_HOST'],
			:basePath => ENV['TEST_PATH'],
			:path => 'ejp_base_registry',
			:response_description => 'The response is a binary (1/0), success or failure',
			:schemas => schemas,
			:fairsharing_key_location => ENV['FAIRSHARING_KEY'],
			:debug => false				 				 
})

if (!cgi.request_method or cgi.request_method == "GET") and !debug
        puts "Content-type: application/openapi+yaml;version=3.0\n\n"
        puts @swagger.getSwagger
elsif cgi.request_method == "POST" or debug
        input_json = JSON.parse(@input)
        guid = input_json["subject"]
        @swagger.testedGUID = guid
        response = testGUID
        puts "Content-type: application/json+ld\n\n"
        puts response
end
