#!/home/mark_moby_wilkinson/.rvm/rubies/ruby-2.5.1/bin/ruby
require './fair_metrics_utilities.rb'
require 'cgi'
require 'json'
require 'uri'

debug = false
VERSION = HARVESTER_VERSION + ":" + "Tst-0.2.3"


def testGUID

	@swagger.addComment("INFO: TEST VERSION '#{VERSION}'\n")
	@swagger.addComment("INFO: END OF HARVESTING\n") # necessary for consistency
	
	guid = @swagger.testedGUID
	
	type = Utils::typeit(guid)  

	if !type
		@swagger.addComment("FAILURE: The GUID identifier of the metadata #{guid} did not match any known identification system.\n")
		@swagger.score = 0
	elsif type == "uri"
		@swagger.addComment("INFO: The metadata GUID appears to be a URL.  Testing known URL persistence schemas (purl, oclc, fdlp, purlz, w3id, ark, doi(as URL)).\n")
		if (guid =~ /(purl)\./) or (guid =~ /(oclc)\./) or(guid =~ /(fdlp)\./) or (guid =~ /(purlz)\./) or (guid =~ /(w3id)\./) or (guid =~ /(ark)\:/) or (guid =~ /(doi.org)/)
			@swagger.addComment("SUCCESS: The metadata GUID conforms with #{$1}, which is known to be persistent.\n")
			@swagger.score = 1
		else
			@swagger.addComment("FAILURE: The metadata GUID does not conform with any known permanent-URL system.\n")
			@swagger.score = 0
		end
	else 
		@swagger.addComment("SUCCESS: The GUID of the metadata is a #{type}, which is known to be persistent.\n")
		@swagger.score = 1
	end
	
	return @swagger.createEvaluationResponse

	
end



if debug
#	@input = '{"subject": "10.5281/zenodo.1147435"}'  # doi
#	@input = '{"subject": "BSYNRYMUTXBXSQ-UHFFFAOYSA-N"}' # inchi
#	@input = '{"subject": "LFQSCWFLJHTTHZ-UHFFFAOYSA-N"}' # another inchi
#	@input = '{"subject": "20.1000/105"}'  # handle
	@input = '{"subject": "http://w3id.org/Magnaporthe/polyA_Sites"}'  # url

else 
	@input = $stdin.read
end

cgi = CGI.new

schemas = {'subject' => ['string', "the GUID being tested"]}

@swagger = Swagger.new({
			:title => "FAIR Metrics Gen2 - Identifier Persistence",
			:description => "Metric to test if the unique identifier of the metadata resource is likely to be persistent. Known schema are registered in FAIRSharing (https://fairsharing.org/standards/?q=&selected_facets=type_exact:identifier%20schema). For URLs that don't follow a schema in FAIRSharing we test known URL persistence schemas (purl, oclc, fdlp, purlz, w3id, ark).  ",
			:tests_metric => 'https://purl.org/fair-metrics/Gen2_FM_F1B',
			:version => VERSION,
			:applies_to_principle => "F1",
			:organization => 'FAIR Metrics Authoring Group',
			:org_url => 'http://fairmetrics.org',
			:responsible_developer => "Mark D Wilkinson",
			:email => 'markw@illuminae.com',
			:developer_ORCiD => '0000-0001-6960-357X',
			:protocol => ENV['TEST_PROTOCOL'],
			:host => ENV['TEST_HOST'],
			:basePath => ENV['TEST_PATH'],
			:path => 'gen2_metadata_identifier_persistence',
			:response_description => 'The response is a binary (1/0), success or failure',
			:schemas => schemas,
			:fairsharing_key_location => ENV['FAIRSHARING_KEY'],				 				 
})


if (!cgi.request_method or cgi.request_method == "GET")  and !debug
	puts "Content-type: application/openapi+yaml;version=3.0\n\n"
	puts @swagger.getSwagger
	
elsif cgi.request_method == "POST"  or debug
	input_json = JSON.parse(@input)
	guid = input_json["subject"]
	@swagger.testedGUID = guid
	response = testGUID
	puts "Content-type: application/json+ld\n\n"
	puts response
end
