#!/home/mark_moby_wilkinson/.rvm/rubies/ruby-2.5.1/bin/ruby
require_relative 'fair_metrics_utilities'
require 'cgi'
require 'json'
require 'uri'
require 'rdf'
require 'rdf/turtle'
require 'sparql'

debug = false
VERSION = HARVESTER_VERSION + ":" + "Tst-0.3.1"
# 0.3.0 totally new algorithm for testing - checks only one pred from each domain, in alphbetidcal order

def testGUID

	@swagger.addComment("INFO: TEST VERSION '#{VERSION}'\n")
	
	
	guid = @swagger.testedGUID
	
	metadata = Utils::resolveit(guid)  # this is where the magic happens!

	metadata.comments.each do |c|
		@swagger.addComment(c)
	end
	@swagger.score = 0
	
	if metadata.guidtype == "unknown"
		@swagger.addComment("FAILURE: The identifier #{guid} did not match any known identification system\n")
		return @swagger.createEvaluationResponse
	end
	
	g = metadata.graph
	if @swagger.debug
		g.each {|s| $stderr.puts s.subject.to_s + "\tPRED: " + s.predicate.to_s + "\tOBJ: " + s.object.to_s + "\n"}
	end
	
	if g.size > 0  # have we found anything yet?
		@swagger.addComment("INFO: Linked data was found.  Test proceeding\n")
	else
		@swagger.addComment("FAILURE: No linked data metadata was found.  Test is exiting.\n")
		@swagger.score = 0
		return @swagger.createEvaluationResponse
	end

	success = 0  
	count = 0
	
	hosthash = Hash.new()
	$stderr.puts hosthash
	preds = g.map {|s| s.predicate unless (s.predicate.value =~ /1999\/xhtml\// or s.predicate.value =~ /rdf-syntax-ns/) }
	
	preds.compact!
	#$stderr.puts preds
	preds.each {|p| (hosthash[p.host] ||=[]) << p}
	#$stderr.puts hosthash

	hosthash.keys.each do |host|
		predicate = hosthash[host].sort.first
		@swagger.addComment "INFO:  Testing resolution of predicates from the domain #{host}\n"
		$stderr.puts "testing host #{host}"

		count += hosthash[host].uniq.count
		
		case predicate.value
		when /purl.org\/dc\//  # these resolve very slowly, so just accept that they are ok!
			@swagger.addComment "INFO:  resolution of DC predicate #{predicate.value} accepted\n"
			$stderr.puts "adding #{hosthash[host].uniq.count} to successes"
			success += hosthash[host].uniq.count
			next
		when /\/vcard\//   # these resolve very slowly, so just accept that they are ok!
			@swagger.addComment "INFO:  resolution of VCARD predicate #{predicate.value} accepted\n"
			$stderr.puts "adding #{hosthash[host].uniq.count} to successes"
			success += hosthash[host].uniq.count
			next
		when /w3\.org\/ns\/dcat/
			@swagger.addComment "INFO:  resolution of DCAT predicate #{predicate.value} accepted\n"
			$stderr.puts "adding #{hosthash[host].uniq.count} to successes"
			success += hosthash[host].uniq.count
			next
		when /xmlns\.com\/foaf\//
			@swagger.addComment "INFO:  resolution of FOAF predicate #{predicate.value} accepted\n"
			$stderr.puts "adding #{hosthash[host].uniq.count} to successes"
			success += hosthash[host].uniq.count
			next			
		end
		
		@swagger.addComment "INFO:  testing resolution of predicate #{predicate.value}\n"
		metadata2 = Utils::resolveit(predicate.value)  # this  sends the content-negotiation for linked data
		g2 = metadata2.graph
		if g2.size > 0
			@swagger.addComment "INFO:  predicate #{predicate.value} resolved to linked data.\n"
		else
			@swagger.addComment "WARN:  predicate #{predicate.value} did not resolve to linked data.\n"
		end

		@swagger.addComment "INFO: If linked data was found in the previous line, it will now be tested by the following SPARQL query: 'select * where {<#{predicate.value}> ?p ?o}' \n"

		query = SPARQL.parse("select * where {<#{predicate.value}> ?p ?o}")
		results = query.execute(g2)
		if  results.any?
			@swagger.addComment "INFO: Resolving #{predicate.value}returned linked data, including that URI as a triple Subject.\n"
			$stderr.puts "adding #{hosthash[host].uniq.count} to successes"
			success += hosthash[host].uniq.count
		else
			@swagger.addComment "WARN:  predicate #{predicate.value} was not found as the SUBJECT of a triple, indicating that it did not resolve to its definition.\n"
		end
	end
	
	if count > 0 and success >= count * 0.66
		@swagger.addComment("SUCCESS: #{success} of a total of #{count} predicates discovered in the metadata resolved to Linked Data data.  This is sufficient to pass the test.\n")
		@swagger.score = 1
	elsif count ==  0 
		@swagger.addComment("FAILURE: No predicates were found that resolved to Linked Data.\n")
		@swagger.score = 0
	else
		@swagger.addComment("FAILURE: #{success} of a total of #{count} predicates discovered in the metadata resolved to Linked Data data.  The minimum to pass this test is 2/3 (with a minimum of 3 predicates in total).\n")
		@swagger.score = 0		
	end
	
	return @swagger.createEvaluationResponse
end


if debug
#	@input = '{"subject": "10.5281/zenodo.1147435"}'  # doi fail
#	@input = '{"subject": "10.5281/zenodo.1065973"}'  # doi fail
	@input = '{"subject": "BSYNRYMUTXBXSQ-UHFFFAOYSA-N"}' # inchi
#	@input = '{"subject": "LFQSCWFLJHTTHZ-UHFFFAOYSA-N"}' # another inchi
#	@input = '{"subject": "20.1000/105"}'  # handle (fail)
#	@input = '{"subject": "https://ortus.rtu.lv/science/lv/datamodule/303"}'  # handle#
#	@input = '{"subject": "10.18710/3PKATY"}'  # doi fail
#	@input = '{"subject": "10.23698/aida/lnco"}'
#	@input = '{"subject": "10.17045/sthlmuni.9907991.v1"}'
#	@input = '{"subject": "http://hdl.handle.net/11250/2631642"}'  # doi 
#	@input = '{"subject": "10.25504/FAIRsharing.6k0kwd"}'  # doi fail
#        @input = '{"subject": "https://www.ebi.ac.uk/arrayexpress/"}' 
#	@input = '{"subject": "https://catalogue.bbmri.nl/menu/main/app-molgenis-app-biobank-explorer/biobank/report/bbmri-eric:ID:NL_AAAACXPAWTUFCACQK2ME25QAAM"}'

else 
	@input = $stdin.read
end


cgi = CGI.new

schemas = {'subject' => ['string', "the GUID being tested"]}

@swagger = Swagger.new({
			:title => "FAIR Metrics Gen2 - Metadata uses FAIR vocabularies (strong)",
			:description => "Maturity Indicator to test if the linked data metadata uses terms that resolve to linked (FAIR) data.  ",
			:tests_metric => 'https://purl.org/fair-metrics/Gen2_FM_I2B',
			:version => VERSION,
			:applies_to_principle => "I2",
			:organization => 'FAIR Metrics Authoring Group',
			:org_url => 'http://fairmetrics.org',
			:responsible_developer => "Mark D Wilkinson",
			:email => 'markw@illuminae.com',
			:developer_ORCiD => '0000-0001-6960-357X',
			:protocol => ENV['TEST_PROTOCOL'],
			:host => ENV['TEST_HOST'],
			:basePath => ENV['TEST_PATH'],
			:path => 'gen2_metadata_uses_fair_vocabularies_strong',
			:response_description => 'The response is a binary (1/0), success or failure',
			:schemas => schemas,
			:fairsharing_key_location => ENV['FAIRSHARING_KEY'],
			:debug => false				 				 
})

if (!cgi.request_method or cgi.request_method == "GET") and !debug
        puts "Content-type: application/openapi+yaml;version=3.0\n\n"
        puts @swagger.getSwagger
elsif cgi.request_method == "POST" or debug
        input_json = JSON.parse(@input)
        guid = input_json["subject"]
        @swagger.testedGUID = guid
        response = testGUID
        puts "Content-type: application/json+ld\n\n"
        puts response
end
