#!/home/mark_moby_wilkinson/.rvm/rubies/ruby-2.5.1/bin/ruby
require_relative 'fair_metrics_utilities'
require 'cgi'
require 'json'
require 'uri'
require 'rdf'
require 'rdf/turtle'
require 'sparql'

debug = false
VERSION = "0.2"

def testGUID

	@swagger.addComment("INFO: TEST VERSION '#{VERSION}'\n")
	
	
	guid = @swagger.testedGUID
	
	metadata = Utils::resolveit(guid)  # this is where the magic happens!

	metadata.comments.each do |c|
		@swagger.addComment(c)
	end
	@swagger.score = 0
	
	if metadata.guidtype == "unknown"
		@swagger.addComment("FAILURE: The identifier #{guid} did not match any known identification system\n")
		return @swagger.createEvaluationResponse
	end
	
	g = metadata.graph
	if @swagger.debug
		g.each {|s| $stderr.puts s.subject.to_s + "\tPRED: " + s.predicate.to_s + "\tOBJ: " + s.object.to_s + "\n"}
	end
	
	if g.size > 0  # have we found anything yet?
		@swagger.addComment("INFO: Linked data was found.  Test proceeding\n")
	else
		@swagger.addComment("FAILURE: No linked data metadata was found.  Test is exiting.\n")
		@swagger.score = 0
		return @swagger.createEvaluationResponse
	end

	success = 0  # we will accept 5/10 failures
	count = 0
	seen = Array.new
	g.each do |stm|
		break if count>=8
		next if seen.include?stm.predicate.value
		seen << stm.predicate.value
		next if stm.predicate.value =~ /www\.w3\.org\/1999\/xhtml\/vocab/  # this is a very problematic site!
		@swagger.addComment "INFO:  testing resolution of predicate #{stm.predicate.value}\n"
		metadata2 = Utils::resolveit(stm.predicate.value)  # this  sends the content-negotiation for linked data
		g2 = metadata2.graph
		query = SPARQL.parse("select * where {<#{stm.predicate.value}> ?p ?o}")
		results = query.execute(g2)
		if  results.any?
			@swagger.addComment "INFO: Resolving #{stm.predicate.value}returned linked data, including that URI as a triple Subject.\n"
			success += 1
		end
		count += 1
	end
	
	if count > 0 and success >= count * 0.5
		@swagger.addComment("SUCCESS: #{success} of the first #{count} predicates discovered in the metadata resolved to Linked Data data.  This is sufficient to pass the test.\n")
		@swagger.score = 1
	elsif count ==  0 
		@swagger.addComment("FAILURE: No predicates were found that resolved to Linked Data.\n")
		@swagger.score = 0
	else
		@swagger.addComment("FAILURE: #{success} of the first #{count} predicates discovered in the metadata resolved to Linked Data data.  The minimum to pass this test is 50%.\n")
		@swagger.score = 0		
	end
	
	return @swagger.createEvaluationResponse
end


if debug
#	@input = '{"subject": "10.5281/zenodo.1147435"}'  # doi fail
#	@input = '{"subject": "10.5281/zenodo.1065973"}'  # doi fail
#	@input = '{"subject": "BSYNRYMUTXBXSQ-UHFFFAOYSA-N"}' # inchi
#	@input = '{"subject": "LFQSCWFLJHTTHZ-UHFFFAOYSA-N"}' # another inchi
#	@input = '{"subject": "20.1000/105"}'  # handle (fail)
#	@input = '{"subject": "http://w3id.org/Magnaporthe/polyA_Sites"}'  # handle#
#	@input = '{"subject": "http://hdl.handle.net/11250/2631642"}'  # doi 
	@input = '{"subject": "10.25504/FAIRsharing.6k0kwd"}'  # doi fail
#        @input = '{"subject": "https://www.ebi.ac.uk/arrayexpress/"}' 
#	@input = '{"subject": "https://catalogue.bbmri.nl/menu/main/app-molgenis-app-biobank-explorer/biobank/report/bbmri-eric:ID:NL_AAAACXPAWTUFCACQK2ME25QAAM"}'

else 
	@input = $stdin.read
end


cgi = CGI.new

schemas = {'subject' => ['string', "the GUID being tested"]}

@swagger = Swagger.new({
			:title => "FAIR Metrics Gen2 - Metadata uses FAIR vocabularies (strong)",
			:description => "Maturity Indicator to test if the linked data metadata uses terms that resolve to linked (FAIR) data.  ",
			:tests_metric => 'https://purl.org/fair-metrics/Gen2_FM_I2B',
			:version => VERSION,
			:applies_to_principle => "I2",
			:organization => 'FAIR Metrics Authoring Group',
			:org_url => 'http://fairmetrics.org',
			:responsible_developer => "Mark D Wilkinson",
			:email => 'markw@illuminae.com',
			:developer_ORCiD => '0000-0001-6960-357X',
			:protocol => 'https',
			:host => 'w3id.org',
			:basePath => '/FAIR_Tests/tests/',
			:path => 'gen2_metadata_uses_fair_vocabularies_strong',
			:response_description => 'The response is a binary (1/0), success or failure',
			:schemas => schemas,
			:fairsharing_key_location => '../fairsharing.key',
			:debug => false				 				 
})

if (!cgi.request_method or cgi.request_method == "GET") and !debug
        puts "Content-type: application/openapi+yaml;version=3.0\n\n"
        puts @swagger.getSwagger
elsif cgi.request_method == "POST" or debug
        input_json = JSON.parse(@input)
        guid = input_json["subject"]
        @swagger.testedGUID = guid
        response = testGUID
        puts "Content-type: application/json+ld\n\n"
        puts response
end
